spring.application.name=Automated Accounting System

db.ip=192.168.31.84:1433
db.username=test
db.password=test
db.name=gpna-bdrv_test_empty
db.connectionTimeout=10000

spring.datasource.url=jdbc:h2:mem:ringBuffer
spring.datasource.username=admin
spring.datasource.password=admin