spring.application.name=Automated Accounting System

bdrv.db.ip=192.168.31.187:1433
bdrv.db.username=test
bdrv.db.password=test
bdrv.db.name=gpna-bdrv_test_empty
bdrv.db.connectionTimeout=10000
#must be >30000
bdrv.db.maxLifetime=30000
bdrv.db.minimumIdle=5
bdrv.db.maximumPoolSize=20

opc.db.url=opc.tcp://192.168.31.222:16550
opc.db.namespace=1
opc.db.prefix=
opc.db.connection.timeout=1000

spring.datasource.url=jdbc:h2:file:~/db_data/ringBuffer
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.maximumPoolSize=20
spring.datasource.minimumIdle=5


written_logs_buffer_capacity=1000
thrown_logs_buffer_capacity=1000

sp_msr_value_reading_in_seconds=10
sp_msn_status_value_reading_in_seconds=5
sp_transaction_value_reading_in_seconds=10

sp_msr_value_writing_in_seconds=1
sp_msn_status_value_writing_in_seconds=1
sp_transaction_value_writing_in_seconds=1

server.port=2444

logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.level.com.zaxxer.hikari.HikariDataSource=DEBUG

